version: "3.8"

x-variables: &variables
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_HOST: "postgres"
  POSTGRES_DB: "postgres"
  POSTGRES_TEST_DB: "test"
  PGDATA: "/var/lib/postgresql/data/pgdata"

services:
  web:
    build: .
    volumes:
      - './:/app'
    depends_on:
      - postgres
    ports:
      - "8881:8080"
    environment:
      <<: *variables
      APP_UVICORN_OPTIONS: "--reload --reload-dir app --host 0.0.0.0 --port=8080"
    env_file:
      - .env

  postgres:
    image: postgres:12.9
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  postgres:
