"""Initialize database

Revision ID: 885b93cf4f6a
Revises: 
Create Date: 2022-04-06 09:21:46.905450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885b93cf4f6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country')),
    sa.UniqueConstraint('name', name=op.f('uq_country_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country')
    # ### end Alembic commands ###
